indice:
   path: /
   controller: App\Controller\Controller::indice

contacto:
   path: /contacto
   controller: App\Controller\Controller::contacto

productos:
   path: /productos
   controller: App\Controller\Controller::productos

servicios:
   path: /servicios
   controller: App\Controller\Controller::servicios



producto_nuevo:
  path: /nuevo
  controller: App\Controller\Controller::nuevoProducto

producto_ver:
  path: /productoVer
  controller: App\Controller\Controller::verProducto

producto_editar:
  path: /editarProducto/{id}
  controller: App\Controller\Controller::editarProducto

producto_borrar:
  path: /borrarProducto/{id}
  controller: App\Controller\Controller::borrarProducto