indice:
  path: /
  controller: App\Controller\Controller::indice

contacto:
  path: /contacto
  controller: App\Controller\Controller::contacto

productos:
  path: /productos
  controller: App\Controller\Controller::productos

servicios:
  path: /servicios
  controller: App\Controller\Controller::servicios

carrito:
  path: /carrito
  controller: App\Controller\Controller::carrito

producto_nuevo:
  path: /productos/nuevo
  controller: App\Controller\ProductController::nuevoProducto

producto_creado:
  path: /productos/creado
  controller: App\Controller\Controller::creadoProducto

producto_ver:
  path: /productos/{id}
  controller: App\Controller\Controller::verProducto

producto_editar:
  path: /productos/{id}/editar
  controller: App\Controller\Controller::editarProducto

producto_borrar:
  path: /productos/{id}/borrar
  controller: App\Controller\Controller::borrarProducto
