indice:
  path: /
  controller: App\Controller\Controller::indice

menu:
  path: /menu/{seccionActual}
  controller: App\Controller\Controller::menu

contacto:
  path: /contacto
  controller: App\Controller\Controller::contacto

productos:
  path: /productos
  controller: App\Controller\Controller::productos

servicios:
  path: /servicios
  controller: App\Controller\Controller::servicios

carrito:
  path: /carrito
  controller: App\Controller\Controller::carrito

carrito_añadir:
  path: /carrito/add/{idProduct}/{quantity}
  controller: App\Controller\CartController::addAction

carrito_borrar:
  path: /carrito/delete/{idCartContent}
  controller: App\Controller\CartController::removeAction

pedido:
  path: /pedido
  controller: App\Controller\OrderController::addAction

producto_nuevo:
  path: /productos/nuevo
  controller: App\Controller\ProductController::nuevoProducto

producto_ver:
  path: /productos/{id}
  controller: App\Controller\Controller::verProducto

producto_editar:
  path: /productos/{id}/editar
  controller: App\Controller\Controller::editarProducto

producto_borrar:
  path: /productos/{id}/borrar
  controller: App\Controller\Controller::borrarProducto
